var StatLookup = [
  {
    "Evolution": "AeroVeedramon",
    "HP": "9500",
    "MP": "-",
    "Strength": "800",
    "Stamina": "700",
    "Wisdom": "-",
    "Speed": "800",
    "Weight": "35",
    "Mistakes": "<=2",
    "Bond": "70",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "Veedramon",
    "Key Points": "6"
  },
  {
    "Evolution": "Agumon",
    "HP": "1900",
    "MP": "-",
    "Strength": "890",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Agumon (Black)",
    "HP": "150",
    "MP": "-",
    "Strength": "10",
    "Stamina": "40",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Agunimon",
    "HP": "54000",
    "MP": "-",
    "Strength": "4800",
    "Stamina": "3900",
    "Wisdom": "-",
    "Speed": "3900",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Alphamon",
    "HP": "24000",
    "MP": "24000",
    "Strength": "5000",
    "Stamina": "4600",
    "Wisdom": "4400",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Angemon",
    "HP": "-",
    "MP": "4800",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "500",
    "Speed": "400",
    "Weight": "",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "50",
    "Wins": "-",
    "Key Digimon": "Patamon",
    "Key Points": "5"
  },
  {
    "Evolution": "Angewomon",
    "HP": "-",
    "MP": "6000",
    "Strength": "600",
    "Stamina": "",
    "Wisdom": "700",
    "Speed": "500",
    "Weight": "<=34",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "70",
    "Wins": "",
    "Key Digimon": "Gatomon",
    "Key Points": "7"
  },
  {
    "Evolution": "Antylamon",
    "HP": "-",
    "MP": "-",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "750",
    "Speed": "900",
    "Weight": "35",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "70",
    "Wins": "-",
    "Key Digimon": "Turuiemon",
    "Key Points": "6"
  },
  {
    "Evolution": "Arresterdramon",
    "HP": "11400",
    "MP": "3000",
    "Strength": "1000",
    "Stamina": "600",
    "Wisdom": "",
    "Speed": "",
    "Weight": "-",
    "Mistakes": "",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Aruraumon",
    "HP": "-",
    "MP": "150",
    "Strength": "20",
    "Stamina": "-",
    "Wisdom": "30",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "BanchoLeomon",
    "HP": "10000",
    "MP": "-",
    "Strength": "1250",
    "Stamina": "1050",
    "Wisdom": "",
    "Speed": "850",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "60",
    "Wins": "55",
    "Key Digimon": "GrapLeomon",
    "Key Points": ""
  },
  {
    "Evolution": "Barbamon",
    "HP": "8000",
    "MP": "",
    "Strength": "1900",
    "Stamina": "1400",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "5",
    "Bond": "",
    "Discipline": "<=9",
    "Wins": "45",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Beelzemon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1400",
    "Stamina": "1000",
    "Wisdom": "",
    "Speed": "1800",
    "Weight": "-",
    "Mistakes": "5",
    "Bond": "90",
    "Discipline": "<=9",
    "Wins": "",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Belphemon SM",
    "HP": "20000",
    "MP": "28000",
    "Strength": "3600",
    "Stamina": "5800",
    "Wisdom": "4600",
    "Speed": "-",
    "Weight": "65",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Birdramon",
    "HP": "-",
    "MP": "4800",
    "Strength": "",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "500",
    "Weight": "<=14",
    "Mistakes": "<=5",
    "Bond": "50",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Biyomon",
    "Key Points": "5"
  },
  {
    "Evolution": "Biyomon",
    "HP": "-",
    "MP": "600",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "300",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "BlackGatomon",
    "HP": "-",
    "MP": "4800",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "450",
    "Speed": "450",
    "Weight": "<=14",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "BlackWarGreymon",
    "HP": "10000",
    "MP": "-",
    "Strength": "",
    "Stamina": "1100",
    "Wisdom": "900",
    "Speed": "1000",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=24",
    "Wins": "45",
    "Key Digimon": "MetalGreymon (Blue)",
    "Key Points": "7"
  },
  {
    "Evolution": "BlackWarGrowlmon",
    "HP": "6000",
    "MP": "-",
    "Strength": "900",
    "Stamina": "900",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "70",
    "Discipline": "<=39",
    "Wins": "30",
    "Key Digimon": "",
    "Key Points": "6"
  },
  {
    "Evolution": "BlueMeramon",
    "HP": "3000",
    "MP": "2000",
    "Strength": "400",
    "Stamina": "-",
    "Wisdom": "350",
    "Speed": "400",
    "Weight": "<=35",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "Meramon",
    "Key Points": "6"
  },
  {
    "Evolution": "Boltmon",
    "HP": "10000",
    "MP": "-",
    "Strength": "2000",
    "Stamina": "2200",
    "Wisdom": "-",
    "Speed": "600",
    "Weight": "60",
    "Mistakes": "<=1",
    "Bond": "75",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "BomberNanimon",
    "HP": "4800",
    "MP": "-",
    "Strength": "-",
    "Stamina": "250",
    "Wisdom": "250",
    "Speed": "400",
    "Weight": "-",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "ChaosGallantmon",
    "HP": "",
    "MP": "5000",
    "Strength": "1400",
    "Stamina": "1600",
    "Wisdom": "-",
    "Speed": "1200",
    "Weight": "-",
    "Mistakes": "",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Cherubimon",
    "HP": "10000",
    "MP": "6000",
    "Strength": "-",
    "Stamina": "1600",
    "Wisdom": "2200",
    "Speed": "1800",
    "Weight": "-",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "-",
    "Key Digimon": "Antylamon",
    "Key Points": "7"
  },
  {
    "Evolution": "Chrysalimon",
    "HP": "-",
    "MP": "27000",
    "Strength": "1800",
    "Stamina": "-",
    "Wisdom": "2400",
    "Speed": "1800",
    "Weight": "<=14",
    "Mistakes": "3",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "20",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "ClearAgumon",
    "HP": "300",
    "MP": "-",
    "Strength": "-",
    "Stamina": "50",
    "Wisdom": "50",
    "Speed": "50",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Craniamon",
    "HP": "8500",
    "MP": "7500",
    "Strength": "1700",
    "Stamina": "2200",
    "Wisdom": "1700",
    "Speed": "-",
    "Weight": "60",
    "Mistakes": "0",
    "Bond": "-",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Crusadermon",
    "HP": "10000",
    "MP": "6000",
    "Strength": "1300",
    "Stamina": "1300",
    "Wisdom": "1400",
    "Speed": "1600",
    "Weight": "-",
    "Mistakes": "0",
    "Bond": "-",
    "Discipline": "90",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Daemon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Daemon",
    "HP": "24000",
    "MP": "24000",
    "Strength": "3500",
    "Stamina": "3500",
    "Wisdom": "3500",
    "Speed": "3500",
    "Weight": "50",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "DarkDramon",
    "HP": "10000",
    "MP": "-",
    "Strength": "2200",
    "Stamina": "-",
    "Wisdom": "2000",
    "Speed": "-",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Datamon",
    "HP": "2000",
    "MP": "4000",
    "Strength": "-",
    "Stamina": "600",
    "Wisdom": "700",
    "Speed": "500",
    "Weight": "<=24",
    "Mistakes": "<=1",
    "Bond": "-",
    "Discipline": "65",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Demidevimon",
    "HP": "-",
    "MP": "500",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "130",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Devimon",
    "HP": "-",
    "MP": "2400",
    "Strength": "400",
    "Stamina": "-",
    "Wisdom": "200",
    "Speed": "-",
    "Weight": "<=19",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Diaboromon",
    "HP": "30000",
    "MP": "30000",
    "Strength": "4500",
    "Stamina": "4500",
    "Wisdom": "6000",
    "Speed": "6000",
    "Weight": "-",
    "Mistakes": "10",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Dianamon",
    "HP": "8000",
    "MP": "40000",
    "Strength": "3000",
    "Stamina": "2000",
    "Wisdom": "4000",
    "Speed": "5000",
    "Weight": "<=49",
    "Mistakes": "",
    "Bond": "90",
    "Discipline": "",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "Doumon",
    "HP": "3500",
    "MP": "-",
    "Strength": "400",
    "Stamina": "",
    "Wisdom": "500",
    "Speed": "400",
    "Weight": "<=34",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "Youkomon",
    "Key Points": "6"
  },
  {
    "Evolution": "Duftmon",
    "HP": "8000",
    "MP": "8000",
    "Strength": "1250",
    "Stamina": "1050",
    "Wisdom": "2000",
    "Speed": "1300",
    "Weight": "<=54",
    "Mistakes": "0",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Dynasmon",
    "HP": "8000",
    "MP": "8000",
    "Strength": "1400",
    "Stamina": "1400",
    "Wisdom": "1400",
    "Speed": "1400",
    "Weight": "-",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Etemon",
    "HP": "3500",
    "MP": "-",
    "Strength": "400",
    "Stamina": "400",
    "Wisdom": "-",
    "Speed": "500",
    "Weight": "<=39",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Examon",
    "HP": "8000",
    "MP": "8000",
    "Strength": "2100",
    "Stamina": "1000",
    "Wisdom": "1000",
    "Speed": "1500",
    "Weight": "70",
    "Mistakes": "-",
    "Bond": "75",
    "Discipline": "-",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "ExVeemon",
    "HP": "14400",
    "MP": "-",
    "Strength": "1500",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "1500",
    "Weight": "<=20",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "Veemon",
    "Key Points": "5"
  },
  {
    "Evolution": "Fugamon",
    "HP": "2400",
    "MP": "-",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "600",
    "Weight": "20",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Gabumon",
    "HP": "-",
    "MP": "-",
    "Strength": "-",
    "Stamina": "530",
    "Wisdom": "550",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Gabumon (Black)",
    "HP": "150",
    "MP": "-",
    "Strength": "-",
    "Stamina": "25",
    "Wisdom": "25",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Gaioumon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Gallantmon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1900",
    "Stamina": "2500",
    "Wisdom": "1200",
    "Speed": "-",
    "Weight": "50",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "WarGrowlmon",
    "Key Points": "8"
  },
  {
    "Evolution": "Gankoomon",
    "HP": "8000",
    "MP": "8000",
    "Strength": "1400",
    "Stamina": "1400",
    "Wisdom": "1400",
    "Speed": "1400",
    "Weight": "-",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Gaogamon",
    "HP": "4800",
    "MP": "-",
    "Strength": "400",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "500",
    "Weight": "<=24",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "20",
    "Key Digimon": "Gaomon",
    "Key Points": "5"
  },
  {
    "Evolution": "Gaomon",
    "HP": "-",
    "MP": "-",
    "Strength": "180",
    "Stamina": "180",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Gargomon",
    "HP": "-",
    "MP": "4800",
    "Strength": "-",
    "Stamina": "500",
    "Wisdom": "-",
    "Speed": "400",
    "Weight": "25",
    "Mistakes": "<=5",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "Terriermon",
    "Key Points": "5"
  },
  {
    "Evolution": "Garudamon",
    "HP": "-",
    "MP": "9500",
    "Strength": "-",
    "Stamina": "500",
    "Wisdom": "800",
    "Speed": "1000",
    "Weight": "<=39",
    "Mistakes": "<=2",
    "Bond": "70",
    "Discipline": "40",
    "Wins": "-",
    "Key Digimon": "Birdramon",
    "Key Points": "6"
  },
  {
    "Evolution": "Garurumon",
    "HP": "14400",
    "MP": "-",
    "Strength": "",
    "Stamina": "1500",
    "Wisdom": "-",
    "Speed": "1500",
    "Weight": "<=19",
    "Mistakes": "<=3",
    "Bond": "",
    "Discipline": "",
    "Wins": "15",
    "Key Digimon": "Gabumon",
    "Key Points": ""
  },
  {
    "Evolution": "Garurumon (Black)",
    "HP": "2400",
    "MP": "1000",
    "Strength": "",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "500",
    "Weight": "<=19",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "15",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Gatomon",
    "HP": "-",
    "MP": "7800",
    "Strength": "-",
    "Stamina": "",
    "Wisdom": "600",
    "Speed": "-",
    "Weight": "<=14",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "50",
    "Wins": "15",
    "Key Digimon": "Salamon",
    "Key Points": "5"
  },
  {
    "Evolution": "Gigadramon",
    "HP": "3000",
    "MP": "3000",
    "Strength": "600",
    "Stamina": "600",
    "Wisdom": "",
    "Speed": "600",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Goburimon",
    "HP": "-",
    "MP": "-",
    "Strength": "80",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "100",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "GoldVeedramon",
    "HP": "-",
    "MP": "27000",
    "Strength": "2400",
    "Stamina": "1800",
    "Wisdom": "1800",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "75",
    "Discipline": "50",
    "Wins": "20",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Gomamon",
    "HP": "-",
    "MP": "-",
    "Strength": "50",
    "Stamina": "130",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Gotsumon",
    "HP": "500",
    "MP": "-",
    "Strength": "-",
    "Stamina": "130",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "GranKuwagamon",
    "HP": "7000",
    "MP": "3000",
    "Strength": "1600",
    "Stamina": "1400",
    "Wisdom": "-",
    "Speed": "1200",
    "Weight": "55",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=19",
    "Wins": "45",
    "Key Digimon": "Okuwamon",
    "Key Points": "7"
  },
  {
    "Evolution": "GrapLeomon",
    "HP": "4000",
    "MP": "2000",
    "Strength": "900",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "900",
    "Weight": "",
    "Mistakes": "<=2",
    "Bond": "70",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "",
    "Key Points": "6"
  },
  {
    "Evolution": "Greymon",
    "HP": "14400",
    "MP": "-",
    "Strength": "1500",
    "Stamina": "1500",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "Agumon",
    "Key Points": "5"
  },
  {
    "Evolution": "Greymon (Blue)",
    "HP": "3400",
    "MP": "-",
    "Strength": "500",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "1",
    "Bond": "50",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Growlmon",
    "HP": "-",
    "MP": "-",
    "Strength": "1640",
    "Stamina": "1600",
    "Wisdom": "-",
    "Speed": "1200",
    "Weight": "20",
    "Mistakes": "-",
    "Bond": "50",
    "Discipline": "<=49",
    "Wins": "20",
    "Key Digimon": "Guilmon",
    "Key Points": "5"
  },
  {
    "Evolution": "Growlmon (Orange)",
    "HP": "2400",
    "MP": "-",
    "Strength": "",
    "Stamina": "200",
    "Wisdom": "200",
    "Speed": "200",
    "Weight": "20",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Guardromon",
    "HP": "",
    "MP": "200",
    "Strength": "100",
    "Stamina": "100",
    "Wisdom": "",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "50",
    "Discipline": "50",
    "Wins": "-",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Guardromon (Gold)",
    "HP": "-",
    "MP": "-",
    "Strength": "1240",
    "Stamina": "1600",
    "Wisdom": "1600",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "<=3",
    "Bond": "50",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Guilmon",
    "HP": "1900",
    "MP": "-",
    "Strength": "590",
    "Stamina": "300",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Gumdramon",
    "HP": "1000",
    "MP": "2000",
    "Strength": "100",
    "Stamina": "100",
    "Wisdom": "100",
    "Speed": "480",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Gururumon",
    "HP": "2400",
    "MP": "",
    "Strength": "250",
    "Stamina": "",
    "Wisdom": "-",
    "Speed": "350",
    "Weight": "<=19",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Hackmon",
    "HP": "1500",
    "MP": "3000",
    "Strength": "450",
    "Stamina": "750",
    "Wisdom": "750",
    "Speed": "450",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Hagurumon",
    "HP": "-",
    "MP": "-",
    "Strength": "-",
    "Stamina": "80",
    "Wisdom": "100",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "HerculesKabuterimon",
    "HP": "10000",
    "MP": "",
    "Strength": "1300",
    "Stamina": "1700",
    "Wisdom": "-",
    "Speed": "1200",
    "Weight": "50",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "MegaKabuterimon",
    "Key Points": ""
  },
  {
    "Evolution": "Hyogamon",
    "HP": "1400",
    "MP": "1000",
    "Strength": "600",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "",
    "Weight": "20",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "IceDevimon",
    "HP": "-",
    "MP": "2400",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "300",
    "Weight": "-",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "IceLeomon",
    "HP": "28000",
    "MP": "-",
    "Strength": "2600",
    "Stamina": "2600",
    "Wisdom": "-",
    "Speed": "2300",
    "Weight": "-",
    "Mistakes": "<=2",
    "Bond": "70",
    "Discipline": "60",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Icemon",
    "HP": "-",
    "MP": "2400",
    "Strength": "250",
    "Stamina": "350",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Ikkakumon",
    "HP": "1700",
    "MP": "1700",
    "Strength": "-",
    "Stamina": "500",
    "Wisdom": ".",
    "Speed": "",
    "Weight": "25",
    "Mistakes": "",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "Gomamon",
    "Key Points": ""
  },
  {
    "Evolution": "Imperialdramon DM",
    "HP": "24000",
    "MP": "24000",
    "Strength": "5600",
    "Stamina": "4600",
    "Wisdom": "-",
    "Speed": "3800",
    "Weight": "65",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "55",
    "Key Digimon": "Paildramon",
    "Key Points": "8"
  },
  {
    "Evolution": "Infermon",
    "HP": "27000",
    "MP": "27000",
    "Strength": "3300",
    "Stamina": "3000",
    "Wisdom": "3000",
    "Speed": "3300",
    "Weight": "-",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "40",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Jesmon",
    "HP": "20000",
    "MP": "28000",
    "Strength": "3600",
    "Stamina": "3300",
    "Wisdom": "3300",
    "Speed": "3800",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Jijimon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "1150",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "",
    "Key Points": "7"
  },
  {
    "Evolution": "Justimon",
    "HP": "6000",
    "MP": "10000",
    "Strength": "1900",
    "Stamina": "-",
    "Wisdom": "2200",
    "Speed": "1500",
    "Weight": "<=34",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Kabuterimon",
    "HP": "-",
    "MP": "-",
    "Strength": "500",
    "Stamina": "500",
    "Wisdom": "-",
    "Speed": "380",
    "Weight": "20",
    "Mistakes": "<=5",
    "Bond": "-",
    "Discipline": "50",
    "Wins": "20",
    "Key Digimon": "Tentomon",
    "Key Points": "5"
  },
  {
    "Evolution": "KaiserGreymon",
    "HP": "16000",
    "MP": "-",
    "Strength": "3000",
    "Stamina": "1600",
    "Wisdom": "-",
    "Speed": "1000",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Kentaurosmon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1200",
    "Stamina": "1300",
    "Wisdom": "1300",
    "Speed": "1700",
    "Weight": "<=54",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Keramon",
    "HP": "-",
    "MP": "-",
    "Strength": "600",
    "Stamina": "600",
    "Wisdom": "750",
    "Speed": "900",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Kuwagamon",
    "HP": "2400",
    "MP": "-",
    "Strength": "450",
    "Stamina": "150",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "20",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Kuzuhamon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Kyuubimon",
    "HP": "",
    "MP": "2400",
    "Strength": "",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "",
    "Weight": "-",
    "Mistakes": "<=3",
    "Bond": "",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Renamon",
    "Key Points": ""
  },
  {
    "Evolution": "Kyuubimon (Silver)",
    "HP": "-",
    "MP": "2400",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "",
    "Speed": "250",
    "Weight": "",
    "Mistakes": "<=5",
    "Bond": "",
    "Discipline": "50",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "LadyDevimon",
    "HP": "-",
    "MP": "6000",
    "Strength": "600",
    "Stamina": "-",
    "Wisdom": "600",
    "Speed": "600",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "-",
    "Discipline": "<=39",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Leomon",
    "HP": "4800",
    "MP": "-",
    "Strength": "250",
    "Stamina": "250",
    "Wisdom": "-",
    "Speed": "400",
    "Weight": "<=24",
    "Mistakes": "<=3",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Leviamon",
    "HP": "10000",
    "MP": "6000",
    "Strength": "1900",
    "Stamina": "2300",
    "Wisdom": "-",
    "Speed": "1400",
    "Weight": "65",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Lilithmon",
    "HP": "20000",
    "MP": "28000",
    "Strength": "4600",
    "Stamina": "-",
    "Wisdom": "5800",
    "Speed": "3600",
    "Weight": "<=34",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "45",
    "Key Digimon": "",
    "Key Points": "8"
  },
  {
    "Evolution": "Lillymon",
    "HP": "-",
    "MP": "6000",
    "Strength": "400",
    "Stamina": "-",
    "Wisdom": "",
    "Speed": "700",
    "Weight": "",
    "Mistakes": "",
    "Bond": "70",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "Togemon",
    "Key Points": "6"
  },
  {
    "Evolution": "Lillymon",
    "HP": "-",
    "MP": "6000",
    "Strength": "400",
    "Stamina": "-",
    "Wisdom": "",
    "Speed": "700",
    "Weight": "",
    "Mistakes": "",
    "Bond": "70",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Togemon",
    "Key Points": "6"
  },
  {
    "Evolution": "Lopmon",
    "HP": "-",
    "MP": "-",
    "Strength": "50",
    "Stamina": "-",
    "Wisdom": "130",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Lucemon",
    "HP": "5000",
    "MP": "5000",
    "Strength": "2000",
    "Stamina": "2000",
    "Wisdom": "2000",
    "Speed": "2000",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Lucemon FM",
    "HP": "40000",
    "MP": "40000",
    "Strength": "5600",
    "Stamina": "5600",
    "Wisdom": "5600",
    "Speed": "5600",
    "Weight": "-",
    "Mistakes": "0",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "40",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Lucemon SM",
    "HP": "37500",
    "MP": "37500",
    "Strength": "8100",
    "Stamina": "8100",
    "Wisdom": "7800",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "55",
    "Key Digimon": "Lucemon FM",
    "Key Points": "8"
  },
  {
    "Evolution": "MachGaogamon",
    "HP": "-",
    "MP": "9500",
    "Strength": "900",
    "Stamina": "-",
    "Wisdom": "",
    "Speed": "900",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "",
    "Wins": "30",
    "Key Digimon": "Gaogamon",
    "Key Points": "6"
  },
  {
    "Evolution": "Machinedramon",
    "HP": "28000",
    "MP": "20000",
    "Strength": "5000",
    "Stamina": "3800",
    "Wisdom": "2600",
    "Speed": "2600",
    "Weight": "85",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "MagnaAngemon",
    "HP": "9500",
    "MP": "-",
    "Strength": "650",
    "Stamina": "650",
    "Wisdom": "1000",
    "Speed": "0",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "70",
    "Wins": "0",
    "Key Digimon": "Angemon",
    "Key Points": "7"
  },
  {
    "Evolution": "Magnadramon",
    "HP": "10000",
    "MP": "10000",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "2600",
    "Speed": "2600",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "45",
    "Key Digimon": "Angewomon",
    "Key Points": "8"
  },
  {
    "Evolution": "MagnaGarurumon",
    "HP": "-",
    "MP": "16000",
    "Strength": "-",
    "Stamina": "2000",
    "Wisdom": "800",
    "Speed": "2800",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Magnamon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1200",
    "Stamina": "1800",
    "Wisdom": "1200",
    "Speed": "1400",
    "Weight": "-",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Mamemon",
    "HP": "3500",
    "MP": "-",
    "Strength": "500",
    "Stamina": "350",
    "Wisdom": "-",
    "Speed": "450",
    "Weight": "<=20",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=59",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "MarineAngemon",
    "HP": "-",
    "MP": "4000",
    "Strength": "-",
    "Stamina": "700",
    "Wisdom": "700",
    "Speed": "1400",
    "Weight": "<=19",
    "Mistakes": "<=1",
    "Bond": "75",
    "Discipline": "75",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Megadramon",
    "HP": "3500",
    "MP": "3500",
    "Strength": "350",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "300",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "MegaGargomon",
    "HP": "10000",
    "MP": "-",
    "Strength": "1200",
    "Stamina": "1700",
    "Wisdom": "1300",
    "Speed": "-",
    "Weight": "60",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "Rapidmon",
    "Key Points": "7"
  },
  {
    "Evolution": "MegaKabuterimon",
    "HP": "9500",
    "MP": "",
    "Strength": "800",
    "Stamina": "750",
    "Wisdom": "-",
    "Speed": "",
    "Weight": "40",
    "Mistakes": "<=2",
    "Bond": "70",
    "Discipline": "",
    "Wins": "30",
    "Key Digimon": "Kabuterimon",
    "Key Points": "6"
  },
  {
    "Evolution": "MegaKabuterimon (Blue)",
    "HP": "2000",
    "MP": "1500",
    "Strength": "300",
    "Stamina": "300",
    "Wisdom": "400",
    "Speed": "300",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "30",
    "Key Digimon": "Kabuterimon",
    "Key Points": "6"
  },
  {
    "Evolution": "MegaSeadramon",
    "HP": "6000",
    "MP": "-",
    "Strength": "",
    "Stamina": "450",
    "Wisdom": "550",
    "Speed": "350",
    "Weight": "",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Meicoomon",
    "HP": "-",
    "MP": "-",
    "Strength": "1320",
    "Stamina": "-",
    "Wisdom": "1320",
    "Speed": "1800",
    "Weight": "<=14",
    "Mistakes": "-",
    "Bond": "50",
    "Discipline": "<=29",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Meramon",
    "HP": "-",
    "MP": "2400",
    "Strength": "350",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "250",
    "Weight": "<=19",
    "Mistakes": "<=5",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "MetalEtemon",
    "HP": "6000",
    "MP": "4000",
    "Strength": "1400",
    "Stamina": "1400",
    "Wisdom": "-",
    "Speed": "1400",
    "Weight": "60",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=19",
    "Wins": "45",
    "Key Digimon": "Etemon",
    "Key Points": "7"
  },
  {
    "Evolution": "MetalGarurumon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1600",
    "Stamina": "2000",
    "Wisdom": "-",
    "Speed": "2000",
    "Weight": "55",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "",
    "Wins": "45",
    "Key Digimon": "WereGarurumon",
    "Key Points": "8"
  },
  {
    "Evolution": "MetalGarurumon (Black)",
    "HP": "10000",
    "MP": "-",
    "Strength": "1400",
    "Stamina": "1400",
    "Wisdom": "-",
    "Speed": "1400",
    "Weight": "-",
    "Mistakes": "<=1",
    "Bond": "75",
    "Discipline": "<=24",
    "Wins": "-",
    "Key Digimon": "WereGarurumon (Black)",
    "Key Points": "7"
  },
  {
    "Evolution": "MetalGreymon",
    "HP": "28000",
    "MP": "-",
    "Strength": "3300",
    "Stamina": "2100",
    "Wisdom": "-",
    "Speed": "2100",
    "Weight": "40",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "Greymon",
    "Key Points": "7"
  },
  {
    "Evolution": "MetalGreymon (Blue)",
    "HP": "6000",
    "MP": "-",
    "Strength": "700",
    "Stamina": "500",
    "Wisdom": "-",
    "Speed": "600",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "",
    "Discipline": "<=49",
    "Wins": "30",
    "Key Digimon": "Greymon (Blue)",
    "Key Points": "6"
  },
  {
    "Evolution": "MetalMamemon",
    "HP": "9500",
    "MP": "-",
    "Strength": "700",
    "Stamina": "900",
    "Wisdom": "700",
    "Speed": "-",
    "Weight": "<=25",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=59",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "MetalSeadramon",
    "HP": "5000",
    "MP": "5000",
    "Strength": "900",
    "Stamina": "1100",
    "Wisdom": "1100",
    "Speed": "1100",
    "Weight": "60",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "MegaSeadramon",
    "Key Points": "7"
  },
  {
    "Evolution": "MetalTyrannomon",
    "HP": "28000",
    "MP": "-",
    "Strength": "3000",
    "Stamina": "2600",
    "Wisdom": "-",
    "Speed": "1900",
    "Weight": "45",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "30",
    "Key Digimon": "Tyrannomon",
    "Key Points": "6"
  },
  {
    "Evolution": "Meteormon",
    "HP": "3500",
    "MP": "-",
    "Strength": "300",
    "Stamina": "400",
    "Wisdom": "300",
    "Speed": "300",
    "Weight": "45",
    "Mistakes": "<=2",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "25",
    "Key Digimon": "",
    "Key Points": "6"
  },
  {
    "Evolution": "Minervamon",
    "HP": "40000",
    "MP": "8000",
    "Strength": "5000",
    "Stamina": "4000",
    "Wisdom": "2000",
    "Speed": "3000",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "55",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "MirageGaogamon",
    "HP": "10000",
    "MP": "-",
    "Strength": "1100",
    "Stamina": "900",
    "Wisdom": "900",
    "Speed": "1300",
    "Weight": "<=49",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "MachGaogamon",
    "Key Points": "7"
  },
  {
    "Evolution": "MirageGaogamon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Monzaemon",
    "HP": "6000",
    "MP": "-",
    "Strength": "600",
    "Stamina": "700",
    "Wisdom": "500",
    "Speed": "-",
    "Weight": "40",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Myotismon",
    "HP": "28000",
    "MP": "-",
    "Strength": "2300",
    "Stamina": "-",
    "Wisdom": "2800",
    "Speed": "2400",
    "Weight": "-",
    "Mistakes": "<=1",
    "Bond": "-",
    "Discipline": "<=39",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Nanimon",
    "HP": "",
    "MP": "-",
    "Strength": "",
    "Stamina": "150",
    "Wisdom": "-",
    "Speed": "",
    "Weight": "-",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": "4"
  },
  {
    "Evolution": "Ogremon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "100",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "",
    "Mistakes": "",
    "Bond": "-",
    "Discipline": "",
    "Wins": "20",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Okuwamon",
    "HP": "6000",
    "MP": "-",
    "Strength": "500",
    "Stamina": "400",
    "Wisdom": "400",
    "Speed": "500",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=39",
    "Wins": "30",
    "Key Digimon": "Kuwagamon",
    "Key Points": "6"
  },
  {
    "Evolution": "OmniShoutmon",
    "HP": "3000",
    "MP": "11400",
    "Strength": "400",
    "Stamina": "600",
    "Wisdom": "1000",
    "Speed": "1000",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "OmniShoutmon",
    "HP": "20000",
    "MP": "11400",
    "Strength": "400",
    "Stamina": "600",
    "Wisdom": "1000",
    "Speed": "1000",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "Ophanimon",
    "HP": "8000",
    "MP": "2000",
    "Strength": "-",
    "Stamina": "1500",
    "Wisdom": "1400",
    "Speed": "1300",
    "Weight": "<=49",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "",
    "Key Points": "8"
  },
  {
    "Evolution": "Palmon",
    "HP": "800",
    "MP": "1000",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Patamon",
    "HP": "600",
    "MP": "-",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Phoenixmon",
    "HP": "8000",
    "MP": "9000",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "1800",
    "Speed": "1600",
    "Weight": "<=44",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "-",
    "Key Digimon": "Garudamon",
    "Key Points": "7"
  },
  {
    "Evolution": "Piddomon",
    "HP": "-",
    "MP": "2400",
    "Strength": "-",
    "Stamina": "",
    "Wisdom": "300",
    "Speed": "300",
    "Weight": "<=19",
    "Mistakes": "",
    "Bond": "-",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Piedmon",
    "HP": "4000",
    "MP": "6000",
    "Strength": "900",
    "Stamina": "-",
    "Wisdom": "1800",
    "Speed": "1500",
    "Weight": "<=34",
    "Mistakes": "5",
    "Bond": "-",
    "Discipline": "<=9",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "PlatinumNumemon",
    "HP": "4000",
    "MP": "-",
    "Strength": "500",
    "Stamina": "",
    "Wisdom": "700",
    "Speed": "",
    "Weight": "60",
    "Mistakes": "",
    "Bond": "75",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "",
    "Key Points": "7"
  },
  {
    "Evolution": "PlatinumNumemon",
    "HP": "4000",
    "MP": "-",
    "Strength": "500",
    "Stamina": "950",
    "Wisdom": "700",
    "Speed": "650",
    "Weight": "60",
    "Mistakes": "-",
    "Bond": "75",
    "Discipline": "75",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "7"
  },
  {
    "Evolution": "Psychemon",
    "HP": "-",
    "MP": "300",
    "Strength": "50",
    "Stamina": ".",
    "Wisdom": "50",
    "Speed": "50",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Rapidmon",
    "HP": "6000",
    "MP": "-",
    "Strength": "600",
    "Stamina": "",
    "Wisdom": "600",
    "Speed": "600",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "40",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Gargomon",
    "Key Points": "6"
  },
  {
    "Evolution": "Rapidmon",
    "HP": "6000",
    "MP": "-",
    "Strength": "600",
    "Stamina": "",
    "Wisdom": "600",
    "Speed": "600",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "40",
    "Discipline": "40",
    "Wins": "-",
    "Key Digimon": "Gargomon",
    "Key Points": "6"
  },
  {
    "Evolution": "Rapidmon (Gold)",
    "HP": "54000",
    "MP": "",
    "Strength": "",
    "Stamina": "2700",
    "Wisdom": "",
    "Speed": "6500",
    "Weight": "<=39",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": "6"
  },
  {
    "Evolution": "RedVeedramon",
    "HP": "4800",
    "MP": "-",
    "Strength": "550",
    "Stamina": "350",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "<=1",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "20",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "RedVegiemon",
    "HP": "1700",
    "MP": "1700",
    "Strength": "500",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "<=19",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "Renamon",
    "HP": "-",
    "MP": "1000",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "80",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Rosemon",
    "HP": "",
    "MP": "10000",
    "Strength": "-",
    "Stamina": "1100",
    "Wisdom": "1700",
    "Speed": "",
    "Weight": "<=35",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "RustTyrannomon",
    "HP": "16000",
    "MP": "-",
    "Strength": "2100",
    "Stamina": "1900",
    "Wisdom": "-",
    "Speed": "1600",
    "Weight": "55",
    "Mistakes": "-",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "MetalTyrannomon",
    "Key Points": "7"
  },
  {
    "Evolution": "Saberdramon",
    "HP": "-",
    "MP": "1200",
    "Strength": "75",
    "Stamina": "-",
    "Wisdom": "75",
    "Speed": "150",
    "Weight": "<=14",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Sakuyamon",
    "HP": "-",
    "MP": "10000",
    "Strength": "1100",
    "Stamina": "-",
    "Wisdom": "1700",
    "Speed": "1400",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Taomon",
    "Key Points": "7"
  },
  {
    "Evolution": "Salamon",
    "HP": "-",
    "MP": "-",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "150",
    "Speed": "210",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Seadramon",
    "HP": "1000",
    "MP": "700",
    "Strength": "",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "250",
    "Weight": "",
    "Mistakes": "<=5",
    "Bond": "-",
    "Discipline": "",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "Seraphimon",
    "HP": "16000",
    "MP": "-",
    "Strength": "1800",
    "Stamina": "-",
    "Wisdom": "2100",
    "Speed": "1700",
    "Weight": "<=44",
    "Mistakes": "0",
    "Bond": "90",
    "Discipline": "90",
    "Wins": "45",
    "Key Digimon": "MagnaAngemon",
    "Key Points": "8"
  },
  {
    "Evolution": "Shamanmon",
    "HP": "-",
    "MP": "-",
    "Strength": "15",
    "Stamina": "-",
    "Wisdom": "50",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "ShineGreymon",
    "HP": "6000",
    "MP": "10000",
    "Strength": "1600",
    "Stamina": "1200",
    "Wisdom": "1350",
    "Speed": "1450",
    "Weight": "50",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "-",
    "Key Points": "8"
  },
  {
    "Evolution": "Shoutmon",
    "HP": "2000",
    "MP": "1000",
    "Strength": "480",
    "Stamina": "100",
    "Wisdom": "100",
    "Speed": "100",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "SkullGreymon",
    "HP": "3000",
    "MP": "3000",
    "Strength": "900",
    "Stamina": "900",
    "Wisdom": "-",
    "Speed": "",
    "Weight": "<=44",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "SnowAgumon",
    "HP": "-",
    "MP": "300",
    "Strength": "-",
    "Stamina": "50",
    "Wisdom": "50",
    "Speed": "50",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "SnowGoburimon",
    "HP": "500",
    "MP": "500",
    "Strength": "-",
    "Stamina": "30",
    "Wisdom": "-",
    "Speed": "50",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Solarmon",
    "HP": "150",
    "MP": "150",
    "Strength": "35",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Sorcermon",
    "HP": "-",
    "MP": "2400",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "350",
    "Speed": "250",
    "Weight": "<=19",
    "Mistakes": "<=3",
    "Bond": "-.",
    "Discipline": "50",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Stingmon",
    "HP": "14400",
    "MP": "-",
    "Strength": "-",
    "Stamina": "1500",
    "Wisdom": "1500",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "<=5",
    "Bond": "50",
    "Discipline": "50",
    "Wins": "-",
    "Key Digimon": "Wormmon",
    "Key Points": "5"
  },
  {
    "Evolution": "Taomon",
    "HP": "-",
    "MP": "6000",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "500",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Kyuubimon",
    "Key Points": ""
  },
  {
    "Evolution": "Taomon",
    "HP": "",
    "MP": "6000",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "500",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "-",
    "Key Digimon": "Kyuubimon",
    "Key Points": ""
  },
  {
    "Evolution": "Taomon (Silver)",
    "HP": "",
    "MP": "6000",
    "Strength": "450",
    "Stamina": "300",
    "Wisdom": "600",
    "Speed": "450",
    "Weight": "<=34",
    "Mistakes": "<=2",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "Kyuubimon (Silver)",
    "Key Points": "6"
  },
  {
    "Evolution": "Tentomon",
    "HP": "1500",
    "MP": "-",
    "Strength": "-",
    "Stamina": "210",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Terriermon",
    "HP": "-",
    "MP": "-",
    "Strength": "-",
    "Stamina": "150",
    "Wisdom": "-",
    "Speed": "210",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Titamon",
    "HP": "",
    "MP": "",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "",
    "Key Points": ""
  },
  {
    "Evolution": "Togemon",
    "HP": "2400",
    "MP": "-",
    "Strength": "300",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "<=5",
    "Bond": "",
    "Discipline": "",
    "Wins": "",
    "Key Digimon": "Palmon",
    "Key Points": "5"
  },
  {
    "Evolution": "ToyAgumon",
    "HP": "-",
    "MP": "1000",
    "Strength": "-",
    "Stamina": "80",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "ToyAgumon (Black)",
    "HP": "-",
    "MP": "150",
    "Strength": "40",
    "Stamina": "10",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Tsukaimon",
    "HP": "150",
    "MP": "100",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "40",
    "Speed": "",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "3"
  },
  {
    "Evolution": "Turuiemon",
    "HP": "-",
    "MP": "",
    "Strength": "300",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "240",
    "Weight": "<=19",
    "Mistakes": "1",
    "Bond": "-",
    "Discipline": "<=49",
    "Wins": "15",
    "Key Digimon": "Lopmon",
    "Key Points": "5"
  },
  {
    "Evolution": "Tyrannomon",
    "HP": "1200",
    "MP": "-",
    "Strength": "150",
    "Stamina": "150",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "UlforceVeedramon",
    "HP": "48000",
    "MP": "-",
    "Strength": "4200",
    "Stamina": "-",
    "Wisdom": "3800",
    "Speed": "6000",
    "Weight": "<=49",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "AeroVeedramon",
    "Key Points": "8"
  },
  {
    "Evolution": "Veedramon",
    "HP": "4800",
    "MP": "-",
    "Strength": "500",
    "Stamina": "400",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "20",
    "Mistakes": "<=5",
    "Bond": "50",
    "Discipline": "-",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": "5"
  },
  {
    "Evolution": "Veemon",
    "HP": "-",
    "MP": "-",
    "Strength": "210",
    "Stamina": "-",
    "Wisdom": "-",
    "Speed": "150",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Vegiemon",
    "HP": "600",
    "MP": "600",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "300",
    "Speed": "",
    "Weight": "<=19",
    "Mistakes": "3",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "VenomMyotismon",
    "HP": "10000",
    "MP": "-",
    "Strength": "1000",
    "Stamina": "500",
    "Wisdom": "1200",
    "Speed": "1500",
    "Weight": "60",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=19",
    "Wins": "45",
    "Key Digimon": "Myotismon",
    "Key Points": "7"
  },
  {
    "Evolution": "Vikemon",
    "HP": "10000",
    "MP": "-",
    "Strength": "1400",
    "Stamina": "",
    "Wisdom": "1200",
    "Speed": "-",
    "Weight": "60",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "-",
    "Wins": "45",
    "Key Digimon": "Zudomon",
    "Key Points": "7"
  },
  {
    "Evolution": "WarGreymon",
    "HP": "16000",
    "MP": "-",
    "Strength": "2100",
    "Stamina": "1700",
    "Wisdom": "-",
    "Speed": "1800",
    "Weight": "55",
    "Mistakes": "<=1",
    "Bond": "90",
    "Discipline": "75",
    "Wins": "45",
    "Key Digimon": "MetalGreymon",
    "Key Points": "8"
  },
  {
    "Evolution": "WarGrowlmon",
    "HP": "9500",
    "MP": "-",
    "Strength": "800",
    "Stamina": "800",
    "Wisdom": "",
    "Speed": "700",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "70",
    "Discipline": "<=49",
    "Wins": "30",
    "Key Digimon": "",
    "Key Points": "7"
  },
  {
    "Evolution": "WarGrowlmon (Orange)",
    "HP": "1000",
    "MP": "",
    "Strength": "600",
    "Stamina": "700",
    "Wisdom": "",
    "Speed": "",
    "Weight": "40",
    "Mistakes": "<=2",
    "Bond": "",
    "Discipline": "40",
    "Wins": "",
    "Key Digimon": "Growlmon (Orange)",
    "Key Points": "6"
  },
  {
    "Evolution": "WaruSeadramon",
    "HP": "6000",
    "MP": "-",
    "Strength": "400",
    "Stamina": "400",
    "Wisdom": "500",
    "Speed": "500",
    "Weight": "40",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "<=29",
    "Wins": "30",
    "Key Digimon": "-",
    "Key Points": "6"
  },
  {
    "Evolution": "WereGarurumon",
    "HP": "19000",
    "MP": "19000",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "3000",
    "Speed": "3500",
    "Weight": "<=39",
    "Mistakes": "<=1",
    "Bond": "70",
    "Discipline": "40",
    "Wins": "-",
    "Key Digimon": "Garurumon",
    "Key Points": "7"
  },
  {
    "Evolution": "WereGarurumon (Black)",
    "HP": "6000",
    "MP": "",
    "Strength": "-",
    "Stamina": "550",
    "Wisdom": "",
    "Speed": "700",
    "Weight": "<=39",
    "Mistakes": "-",
    "Bond": "",
    "Discipline": "",
    "Wins": "30",
    "Key Digimon": "Garurumon(Black)",
    "Key Points": "6"
  },
  {
    "Evolution": "Wizardmon",
    "HP": "",
    "MP": "2400",
    "Strength": "",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "<=19",
    "Mistakes": "<=5",
    "Bond": "",
    "Discipline": "",
    "Wins": "15",
    "Key Digimon": "-",
    "Key Points": ""
  },
  {
    "Evolution": "Woodmon",
    "HP": "1400",
    "MP": "1000",
    "Strength": "300",
    "Stamina": "300",
    "Wisdom": "-",
    "Speed": "-",
    "Weight": "<=19",
    "Mistakes": "<=5",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Wormmon",
    "HP": "1000",
    "MP": "-",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "80",
    "Speed": "-",
    "Weight": "-",
    "Mistakes": "-",
    "Bond": "-",
    "Discipline": "-",
    "Wins": "-",
    "Key Digimon": "-",
    "Key Points": "2"
  },
  {
    "Evolution": "Youkomon",
    "HP": "-",
    "MP": "2400",
    "Strength": "-",
    "Stamina": "-",
    "Wisdom": "400",
    "Speed": "200",
    "Weight": "<=19",
    "Mistakes": "<=5",
    "Bond": "",
    "Discipline": "50",
    "Wins": "",
    "Key Digimon": "-",
    "Key Points": "4"
  },
  {
    "Evolution": "Zudomon",
    "HP": "",
    "MP": "-",
    "Strength": "800",
    "Stamina": "",
    "Wisdom": "",
    "Speed": "",
    "Weight": "",
    "Mistakes": "",
    "Bond": "",
    "Discipline": "-",
    "Wins": "30",
    "Key Digimon": "",
    "Key Points": ""
  }
]